# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build & Test

on:
  push:
    branches: [ main ] # TODO: Change back to master for opensha/opensha
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew -Dorg.gradle.internal.http.connectionTimeout=60000 -Dorg.gradle.internal.http.socketTimeout=300000 assemble
    - name: Run standard tests with Gradle
      run: ./gradlew -Dorg.gradle.internal.http.connectionTimeout=60000 -Dorg.gradle.internal.http.socketTimeout=300000 testVerbose
    - name: Notify Slack on failure
      if: ${{ failure() }}
      uses: slackapi/slack-github-action@v2
      with:
        # choose method: 'incoming-webhook' (with webhook_url) or 'bot' (with bot token)
        slack-webhook-url: ${{ secrets.SLACK_WEBHOOK }}   # TODO: Add secret in main repo
        msg: |
          :x: *Workflow failed*
          Repo: `${{ github.repository }}`
          Workflow: `${{ github.workflow }}`
          Run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>
